const pptxgen = require('pptxgenjs');
const puppeteer = require('puppeteer');
const docx = require('docx');
const fs = require('fs');
const path = require('path');

async function generateReport() {
    const args = process.argv.slice(2);
    if (args.length < 3) {
        console.error("Usage: node generate_report.js <format> <outputFile> <contentFile>");
        process.exit(1);
    }

    const format = args[0];
    const outputFile = args[1];
    const contentFile = args[2];

    let content = "";
    try {
        content = fs.readFileSync(contentFile, 'utf8');
    } catch (e) {
        console.error(`Error reading content file: ${e.message}`);
        process.exit(1);
    }

    try {
        if (format === 'ppt' || format === 'pptx') {
            let pres = new pptxgen();
            // Title Slide
            let slide = pres.addSlide();
            slide.addText("Research Report", { x: 1, y: 1, fontSize: 32, bold: true, color: '363636' });
            slide.addText("Generated by DeepResearcher", { x: 1, y: 2, fontSize: 18, color: '737373' });

            // Content Slides (simple chunking)
            // Improved chunking to split by paragraphs roughly
            const charsPerSlide = 800;
            const chunks = content.match(new RegExp(`.{1,${charsPerSlide}}`, 'g')) || [content];

            chunks.forEach((chunk, i) => {
                let slide = pres.addSlide();
                slide.addText(`Page ${i + 1}`, { x: 0.5, y: 0.2, fontSize: 12, color: 'AAAAAA' });
                slide.addText(chunk, { x: 0.5, y: 0.5, w: '90%', h: '80%', fontSize: 16, color: '363636', align: 'left' });
            });
            await pres.writeFile({ fileName: outputFile });

            // pptxgenjs automatically adds .pptx if missing, or sometimes appends it.
            // Check if file exists exactly as requested. If not, check with .pptx appended and rename.
            if (!fs.existsSync(outputFile)) {
                if (fs.existsSync(outputFile + ".pptx")) {
                    fs.renameSync(outputFile + ".pptx", outputFile);
                }
            }
            console.log(`PPT generated at ${outputFile}`);

        } else if (format === 'pdf') {
            const browser = await puppeteer.launch({ headless: "new" });
            const page = await browser.newPage();
            // Simple HTML wrap
            const htmlContent = `
            <html>
                <body style="font-family: 'Helvetica', 'Arial', sans-serif; padding: 50px; line-height: 1.6; color: #333;">
                    <h1 style="color: #2c3e50; border-bottom: 2px solid #eee; padding-bottom: 10px;">Research Report</h1>
                    <div style="white-space: pre-wrap; font-size: 14px;">${content}</div>
                    <footer style="margin-top: 50px; font-size: 10px; color: #888; text-align: center;">Generated by DeepResearcher</footer>
                </body>
            </html>`;
            await page.setContent(htmlContent);
            await page.pdf({ path: outputFile, format: 'A4', margin: { top: '20mm', bottom: '20mm', left: '20mm', right: '20mm' } });
            await browser.close();
            console.log(`PDF generated at ${outputFile}`);

        } else if (format === 'docx') {
            const { Document, Packer, Paragraph, TextRun, HeadingLevel } = docx;

            // Split by double newlines for paragraphs
            const paragraphs = content.split('\n').filter(line => line.trim() !== '').map(line =>
                new Paragraph({
                    children: [new TextRun({ text: line, size: 24 })], // 24 = 12pt
                    spacing: { after: 200 }
                })
            );

            const doc = new Document({
                sections: [{
                    properties: {},
                    children: [
                        new Paragraph({
                            text: "Research Report",
                            heading: HeadingLevel.TITLE,
                            spacing: { after: 400 }
                        }),
                        ...paragraphs
                    ],
                }],
            });

            const buffer = await Packer.toBuffer(doc);
            fs.writeFileSync(outputFile, buffer);
            console.log(`DOCX generated at ${outputFile}`);
        } else {
            // Fallback or error
            console.error("Unknown format");
            process.exit(1);
        }
    } catch (err) {
        console.error(`Generation failed: ${err}`);
        process.exit(1);
    }
}

generateReport();
