import os
from fpdf import FPDF
from pptx import Presentation
from pptx.util import Inches

def create_pdf(text: str, filename: str):
    """
    Creates a simple PDF from text.
    """
    pdf = FPDF()
    pdf.add_page()
    pdf.set_font("Arial", size=12)
    
    # Simple line handling
    for line in text.split('\n'):
        # Encode to latin-1 to avoid unicode errors in standard fpdf, or replace characters
        safe_line = line.encode('latin-1', 'replace').decode('latin-1')
        pdf.multi_cell(0, 10, safe_line)
        
    pdf.output(filename)
    return filename

def create_ppt(text: str, filename: str):
    """
    Creates a simple PPT from text. 
    Assumes text is somewhat structured (bullet points).
    """
    prs = Presentation()
    
    # Title Slide
    slide_layout = prs.slide_layouts[0]
    slide = prs.slides.add_slide(slide_layout)
    slide.shapes.title.text = "Research Report"
    slide.placeholders[1].text = "Generated by Autonomous Agent"
    
    # One slide per chunk of text approx
    chunk_size = 800
    text_chunks = [text[i:i+chunk_size] for i in range(0, len(text), chunk_size)]
    
    for i, chunk in enumerate(text_chunks):
        bullet_layout = prs.slide_layouts[1]
        slide = prs.slides.add_slide(bullet_layout)
        shapes = slide.shapes
        shapes.title.text = f"Page {i+1}"
        shapes.placeholders[1].text = chunk
        
    prs.save(filename)
    return filename

from docx import Document

def create_markdown(text: str, filename: str):
    with open(filename, 'w') as f:
        f.write(text)
    return filename

def create_docx(text: str, filename: str):
    """
    Creates a simple Word Doc from text.
    """
    doc = Document()
    doc.add_heading('Research Report', 0)
    
    for line in text.split('\n'):
        doc.add_paragraph(line)
        
    doc.save(filename)
    return filename
